### PR TITLE
build: fix u64 overflow when caching the hash

### LINKED ISSUE #195: cargo cbuild always rebuild the leaf crate
Each time we run `cargo cbuild` the leaf crate is rebuild, despite no code being changed.

This can easily be reproduced using the example-project from the source tree:

```
example-project  (master)$ cargo cbuild 
(...)
example-project  (master)$ cargo cbuild  -v
       Fresh libc v0.2.80
   Compiling example-project v0.1.0 (/var/home/cassidy/dev/rust/cargo-c/example-project)
     Running `rustc --crate-name example_project --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type staticlib --crate-type cdylib --crate-type lib --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C link-arg=-Wl,-soname,libexample_project.so.0 --cfg cargo_c --print native-static-libs --cfg 'feature="capi"' --cfg 'feature="default"' --cfg 'feature="libc"' -C metadata=a88e671a1fdde6e5 --out-dir /var/home/cassidy/dev/rust/cargo-c/example-project/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C incremental=/var/home/cassidy/dev/rust/cargo-c/example-project/target/x86_64-unknown-linux-gnu/debug/incremental -L dependency=/var/home/cassidy/dev/rust/cargo-c/example-project/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/var/home/cassidy/dev/rust/cargo-c/example-project/target/debug/deps --extern libc=/var/home/cassidy/dev/rust/cargo-c/example-project/target/x86_64-unknown-linux-gnu/debug/deps/liblibc-d97a29d036b97b09.rlib -Cpanic=abort`
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
    Building pkg-config files
    Building header file using cbindgen
```

This is [a problem for gst-plugins-rs](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/150) as linking each plugin can take a non-trivial amount of time.

### PR DESCRIPTION
**Pull request by gdesmott**
The hasher is storing the hash as a u64 while toml is parsing it as a i64.
Toml does not support u64, making the parser failing because of the
overflow and so always forcing a rebuild.

Fix it by storing the hash as a string instead.

Fix #195

### CODE REVIEW

File: src/build.rs [hunk 1]
```diff
@@ -333,7 +336,7 @@ impl<'a> FingerPrint<'a> {
         let mut f = std::fs::File::open(&self.path())?;
         let mut cache_str = String::new();
         f.read_to_string(&mut cache_str)?;
-        let cache = toml::de::from_str(&cache_str)?;
+        let cache = toml::de::from_str(&cache_str).unwrap();
```
Comment (lu-zero) [inline src/build.rs:339]: This is potentially spurious.

Comment (gdesmott) [reply src/build.rs]: My bad, it was for debugging and I accidentally recorded it. Removed.
